<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Untitled Form</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
        
        <img id="top" src="top.png" alt="">
        <div id="form_container">
        
                <h1><a>Untitled Form</a></h1>
                <form id="form_120222" class="appnitro"  method="post" action="">
                                        <div class="form_description">
                        <h2>Untitled Form</h2>
                        <p>This is your form description. Click here to edit.</p>
                </div>                                          
                        <ul >
                        
                                        <li id="li_2" >
                <label class="description" for="element_2">Drop Down </label>
                <div>
                <select class="element select medium" id="element_2" name="element_2"> 
                        <option value="" selected="selected"></option>
<option value="AL">Alabama</option>
<option value="AK">Alaska</option>
<option value="AS">American Samoa</option>
<option value="AZ">Arizona</option>
<option value="AR">Arkansas</option>
<option value="CA">California</option>
<option value="CO">Colorado</option>
<option value="CT">Connecticut</option>
<option value="DE">Delaware</option>
<option value="DC">District Of Columbia</option>
<option value="FL">Florida</option>
<option value="GA">Georgia</option>
<option value="GU">Guam</option>
<option value="HI">Hawaii</option>
<option value="ID">Idaho</option>
<option value="IL">Illinois</option>
<option value="IN">Indiana</option>
<option value="IA">Iowa</option>
<option value="KS">Kansas</option>
<option value="KY">Kentucky</option>
<option value="LA">Louisiana</option>
<option value="ME">Maine</option>
<option value="MD">Maryland</option>
<option value="MA">Massachusetts</option>
<option value="MI">Michigan</option>
<option value="MN">Minnesota</option>
<option value="MS">Mississippi</option>
<option value="MO">Missouri</option>
<option value="MT">Montana</option>
<option value="NE">Nebraska</option>
<option value="NV">Nevada</option>
<option value="NH">New Hampshire</option>
<option value="NJ">New Jersey</option>
<option value="NM">New Mexico</option>
<option value="NY">New York</option>
<option value="NC">North Carolina</option>
<option value="ND">North Dakota</option>
<option value="MP">Northern Mariana IS</option>
<option value="OH">Ohio</option>
<option value="OK">Oklahoma</option>
<option value="OR">Oregon</option>
<option value="PA">Pennsylvania</option>
<option value="PR">Puerto Rico</option>
<option value="RI">Rhode Island</option>
<option value="SC">South Carolina</option>
<option value="SD">South Dakota</option>
<option value="TN">Tennessee</option>
<option value="TX">Texas</option>
<option value="UT">Utah</option>
<option value="VT">Vermont</option>
<option value="VA">Virginia</option>
<option value="VI">Virgin Islands</option>
<option value="WA">Washington</option>
<option value="WV">West Virginia</option>
<option value="WI">Wisconsin</option>
<option value="WY">Wyoming</option>
                </select>
                </div> 
                </li>           <li id="li_1" >
                <label class="description" for="element_1">Text </label>
                <div>
                        <input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/> 
                </div> 
                </li>
                        
                                        <li class="buttons">
                            <input type="hidden" name="form_id" value="120222" />
                            
                                <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
                </li>
                        </ul>
                </form> 
                <div id="footer">
                        Generated by <a href="http://www.phpform.org">pForm</a>
                </div>
        </div>
        <img id="bottom" src="bottom.png" alt="">
        </body>
</html>
